import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" suppressHydrationWarning>
      <body className="min-h-screen bg-background text-foreground font-sans antialiased">
        <script
          dangerouslySetInnerHTML={{
            __html: `
(() => {
  try {
    const t = localStorage.getItem("bags_theme") || "default";
    const root = document.documentElement;
    root.classList.remove("theme-neon", "theme-ice");
    if (t === "neon") {
      root.classList.add("theme-neon");
      root.classList.add("dark");
    } else if (t === "ice") {
      root.classList.add("theme-ice");
      root.classList.remove("dark");
    } else {
      root.classList.add("dark");
    }
  } catch {}
})();`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
